# Copyright (c) 2021-2021. TIBCO Software Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file
version: "3.9"
services:

##### Jasper Report Server Web Application
  jasperserver-webapp:
    image: "${JASPERREPORTS_SERVER_APP_IMAGE_NAME}:${JASPERREPORTS_SERVER_APP_IMAGE_TAG}"
    env_file:
      - .env
    build:
      context: ../../../
      dockerfile: ./jaspersoft-containers/Docker/jrs/Dockerfile
      args:
        - INSTALL_CHROMIUM
        - JASPERREPORTS_SERVER_VERSION
        - TOMCAT_BASE_IMAGE
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      JAVA_OPTS: "-Xmx3500M -Djs.license.directory=/usr/local/share/jasperserver-pro/license -Djasperserver.cache.jms.provider=tcp://activemq:61616 "
    volumes:
      - ./resources/keystore:/usr/local/share/jasperserver-pro/keystore
      - ./resources/license/jasperserver.license:/usr/local/share/jasperserver-pro/license/jasperserver.license
    mem_limit: 6g
    mem_reservation: 3g
    cpu_shares: 1000
    depends_on:
      - repository
      # - activemq

##### JasperReportServer repository, import and export configuration
  jasperserver-buildomatic:
    image: "${JASPERREPORTS_SERVER_BUILDOMATIC_IMAGE_NAME}:${JASPERREPORTS_SERVER_BUILDOMATIC_IMAGE_TAG}"
    env_file:
      - .env
    build:
      context: ../../../
      dockerfile: ./jaspersoft-containers/Docker/jrs/Dockerfile.buildomatic
      args:
        - JASPERREPORTS_SERVER_VERSION
        - JDK_BASE_IMAGE
    command: ${JS_INSTALL_TARGETS}
    volumes:
      - ./resources/keystore:/usr/local/share/jasperserver-pro/keystore
    depends_on:
      - repository

 ##### JasperReportServer Repository
  repository:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=localDev
    volumes:
      - mysql-data:/var/lib/mysql
  # We don't use ActiveMQ based session storage
  # activemq:
  #   image: rangareddyv/activemq-openshift:5.16.2
  #   ports:
  #     - 8161:8161
  #     - 61616:61616

volumes:
  mysql-data:
    name: jrs-repository-vol
